setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: 12316
    WORLD_SIZE: 1
    NODE_RANK: 0
  wandb_config:
    project: TAPE_Contact
    name: SaProt_650M_AF2

model:
#    Which model to use
  model_py_path: esm/esm_contact_model
  kwargs:
#    Arguments to initialize the specific class
    config_path: weights/PLMs/SaProt_650M_AF2
    load_pretrained: True

#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 1.0e-2
    #    Weather to use this scheduler or not
    on_use: false

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

  save_path: weights/Contact/SaProt_650M_AF2.pt
  load_prev_scheduler: false
  save_weights_only: true


dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: esm/esm_contact_dataset
  dataloader_kwargs:
    batch_size: 2
    num_workers: 8
  train_lmdb: LMDB/Contact/foldseek/train
  valid_lmdb: LMDB/Contact/foldseek/valid
  test_lmdb: LMDB/Contact/foldseek/test
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: weights/PLMs/SaProt_650M_AF2

#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
  max_epochs: 30
  log_every_n_steps: 1
  strategy:
    find_unused_parameters: False
  logger: False
  enable_checkpointing: false
  val_check_interval: 0.1
  accelerator: gpu
  devices: 1
  num_nodes: 1
  accumulate_grad_batches: 1
  precision: 16
  num_sanity_val_steps: 0