setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: localhost
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0
  wandb_config:
    project: DeepLoc_cls10
    name: SaProt_650M_AF2

model:
#    Which model to use
  model_py_path: esm/esm_classification_model
  kwargs:
#    Arguments to initialize the specific class
    config_path: weights/PLMs/SaProt_650M_AF2
    load_pretrained: True
    num_labels: 10

#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 2.0e-5
#    Weather to use this scheduler or not
    on_use: false

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

  save_path: weights/DeepLoc/cls10/SaProt_650M_AF2.pt


dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: esm/esm_classification_dataset
  dataloader_kwargs:
    batch_size: 1
    num_workers: 8

  train_lmdb: LMDB/DeepLoc/cls10/foldseek/train
  valid_lmdb: LMDB/DeepLoc/cls10/foldseek/valid
  test_lmdb: LMDB/DeepLoc/cls10/foldseek/test
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: weights/PLMs/SaProt_650M_AF2
    plddt_threshold: 70


#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
  max_epochs: 100
  log_every_n_steps: 1
  strategy:
    find_unused_parameters: True
  logger: False
  enable_checkpointing: false
  val_check_interval: 0.5
  accelerator: gpu
  devices: 1
  num_nodes: 1
  accumulate_grad_batches: 1
  precision: 16
  num_sanity_val_steps: 0