setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: 6ed8c632f9676e109dad08100d9b636e69138eb7
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: localhost
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0
  wandb_config:
    project: GO_BP
    name: esm2_t33_650M_UR50D

model:
#    Which model to use
  model_py_path: saprot/saprot_annotation_model
  kwargs:
#    Arguments to initialize the specific class
    config_path: weights/PLMs/esm2_t33_650M_UR50D
    load_pretrained: True
    anno_type: GO_BP

#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 2.0e-5
#    Weather to use this scheduler or not
    on_use: false

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

  save_path: weights/GO/BP/esm2_t33_650M_UR50D.pt


dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: saprot/saprot_annotation_dataset
  dataloader_kwargs:
    batch_size: 4
    num_workers: 8

  train_lmdb: LMDB/GO/AF2/BP/normal/train
  valid_lmdb: LMDB/GO/AF2/BP/normal/valid
  test_lmdb: LMDB/GO/AF2/BP/normal/test
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: weights/PLMs/esm2_t33_650M_UR50D


#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
  max_epochs: 100
  log_every_n_steps: 1
  strategy:
    find_unused_parameters: True
  logger: True
  enable_checkpointing: false
  val_check_interval: 0.5
  accelerator: gpu
  devices: 8
  num_nodes: 1
  accumulate_grad_batches: 2
  precision: 16
  num_sanity_val_steps: 0