setting:
  seed: 20000812
  os_environ:
    CUDA_VISIBLE_DEVICES: 1,2,3,4,5,6,7
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: 12316
    WORLD_SIZE: 1
    NODE_RANK: 0

  out_path: ~
  dataset_dir: LMDB/ClinVar

model:
  model_py_path: esm/esm_mutation_model
  load_prev_scheduler: True
  kwargs:
    config_path: weights/PLMs/esm2_t33_650M_UR50D
    load_pretrained: True
    log_clinvar: True
    log_dir: output/ClinVar/esm2_t33_650M_UR50D

dataset:
  dataset_py_path: mutation_zeroshot_dataset
  dataloader_kwargs:
    batch_size: 16
    num_workers: 8
  kwargs: {}

Trainer:
  log_every_n_steps: 1
  devices: 1
  accelerator: gpu
  num_nodes: 1
  strategy:
    find_unused_parameters: False
  logger: False
