setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0
#      WANDB_MODE: offline
  wandb_config:
    project: pretraining
    name: SaProt_650M_AF2

model:
#    Which model to use
  model_py_path: esm/esm_lm_model
  kwargs:
#    Arguments to initialize the specific class
    config_path: westlake-repl/SaProt_650M_AF2
    load_pretrained: False

#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 0
    max_lr: 4.0e-4
    final_lr: 4.0e-5
    warmup_steps: 2000
    start_decay_after_n_steps: 150000
    end_decay_after_n_steps: 1500000
#    Weather to use this scheduler or not
    on_use: True

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

  save_path: /content/saprot/weights/Pretrain/SaProt_650M_AF2.pt
  load_prev_scheduler: false
  save_weights_only: false


dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: esm/esm_foldseek_dataset
  dataloader_kwargs:
    batch_size: 1
    num_workers: 2

  train_lmdb: /content/saprot/LMDB/AF2_Uniref50/foldseek/train
  valid_lmdb: /content/saprot/LMDB/AF2_Uniref50/foldseek/valid
  test_lmdb: /content/saprot/LMDB/AF2_Uniref50/foldseek/valid
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: westlake-repl/SaProt_650M_AF2
    max_length: 1024
    mask_ratio: 0.15


#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
#  max_epochs: 100
  max_steps: 1000000
  min_steps: 1000000
  log_every_n_steps: 1
  accelerator: gpu
  devices: 1
  accumulate_grad_batches: 1
  num_nodes: 1
  strategy:
    find_unused_parameters: True
  logger: False
  enable_checkpointing: false
  num_sanity_val_steps: 0
  val_check_interval: 100
  precision: 16
  limit_val_batches: 1.0
  limit_test_batches: 1.0

